### PR TITLE
Allow to set additional color information for special charts

### PR DESCRIPTION
**Pull request by jantimon**
The `getDataSets` function copies and extends the colours object.  
This pull request adds the same for the `getData` function.

### CODE REVIEW

**Comment by jantimon** [comment]
@jtblin if you like I could also bump the bower version - do you think this could be merged?

**Comment by jtblin** [comment]
Sorry for the lag mate, I moved house and didn't have internet for a while. Looks good, I'll merge that and make `getDataSets` and `getData` consistently use `extend`.

Bumping the package.json and bower.json is done during the build via the `gulpfile` fyi.

**Comment by jantimon** [comment]
Thanks a lot :)

**Comment by jtblin** [comment]
Thank you for the new contrib :+1:

**Pull request merged**
