### PR TITLE
[issue-199] $timeout causing infinite $apply and infinite times filte…

### PR DESCRIPTION
**Pull request by palsingh**
A recent change in library was to handle chart to render in a tab which is hidden. It uses $timeout to check if its parent is visible or not. When parent is visible, chart renders. It was a much needed upgrade. But now what is happening that $timeout is executing infinitely till the time all charts are not rendered and in result $timeout does is call $apply and $apply is doing its own work. It is becoming very expensive process as in my case, I've lots of filters and few tabs, So every time $timeout is done, it does $apply and $apply is executing filters and it goes on. I would suggest to add false to third param of $timeout so it should not do $apply.
Right now:
```javascript
if (isResponsive(type, scope) && container.clientHeight === 0) {
    return $timeout(function () {
        createChart(type);
    }, 50);
}
```
Should be:
```javascript
if (isResponsive(type, scope) && container.clientHeight === 0) {
    return $timeout(function () {
        createChart(type);
    }, 50, false);
}
```

I hope it make sense.

### CODE REVIEW

**Comment by jtblin** [comment]
Thanks, totally makes sense. Hopefully that won't have other side effects.

For information, I wanted to use the digest cycle originally by watching the height of the element / container instead of adding timeouts but I couldn't as it didn't work reliably unfortunately (needed the code that show the charts to use `$apply` otherwise the `watch` didn't trigger).

**Comment by jantimon** [comment]
maybe we could just measure the client height instead and if it is > 0 we do an apply otherwise we check again in 50ms
this would reduce side effects but I guess there won't be many side effects anyway.

**Comment by jtblin** [comment]
Yes good idea, we could actually just add a call to `$apply` after creating the chart.

**Comment by palsingh** [comment]
Make sense @jtblin

**Pull request merged**
