### PR TITLE
Version, please.

### PR DESCRIPTION
**Pull request by voltechs**
Makes it easier to track dependancies, requirements and what the heck version we're on :)

### CODE REVIEW

**Comment by jtblin** [comment]
Thanks but I don't want to have to modify the version name manually. This is done automatically by the gulp script which updates the package.json and bower.json files e.g. https://github.com/jtblin/angular-chart.js/blob/master/gulpfile.js#L152

**Comment by Roundaround** [comment]
@jtblin @voltechs You could easily set up a gulp task to do such a thing (with a banner task or a regex replacer task - see https://www.npmjs.com/package/gulp-replace).  If a banner is going to be added to the top of the source code, it should be automatically updated with the rest of the versioning tasks.

**Comment by voltechs** [comment]
@Roundaround agreed that's the best solution.

**Comment by jtblin** [comment]
@voltechs are you ok to add the version dynamically with the module suggested by @Roundaround or otherwise? That could be done in the `update` task.

**Comment by jtblin** [comment]
Implemented in d546ffd

**Pull request closed without merging**
