### PR TITLE
make module factory return a module name instead a module instance as…

### PR DESCRIPTION
**Pull request by drpicox**
… angular libraries does

See: https://github.com/angular/bower-angular-animate/blob/fc8c108cbb1d8486f725386b943d35730caf3358/index.js as example:

```javascript
    require('./angular-animate');
    module.exports = 'ngAnimate';
````

So you can do:

```javascript
    module.exports = angular.module('yourModule', [
        require('./yourStuff'),
        require('./moreOfYourStuff'),
        require('angular-animate'),
        require('angular-route'),
        require('angular-chart'),
    ]).name;
```

### CODE REVIEW

**Comment by jtblin** [comment]
Didn't know about that. Is that backward compatible?

**Comment by drpicox** [comment]
Nope, it is not backward compatible, at least in theory.

Why it is not backward compatible?

It is because users are doing:

```javascript
module.exports = angular.module('yourModule', [
    require('./yourStuff'),
    require('./moreOfYourStuff'),
    require('angular-animate'),
    require('angular-route'),
    require('angular-chart').name,
]).name;
```

or

```javascript
require('angular-chart');

module.exports = angular.module('yourModule', [
    require('./yourStuff'),
    require('./moreOfYourStuff'),
    require('angular-animate'),
    require('angular-route'),
    "chart.js",
]).name;
```

With the proposed change people can do:

```javascript
module.exports = angular.module('yourModule', [
    require('./yourStuff'),
    require('./moreOfYourStuff'),
    require('angular-animate'),
    require('angular-route'),
    require('angular-chart'),
]).name;
```

or, not recommended,

```javascript
require('angular-chart');

module.exports = angular.module('yourModule', [
    require('./yourStuff'),
    require('./moreOfYourStuff'),
    require('angular-animate'),
    require('angular-route'),
    "chart.js",
]).name;
```

So, in the worst case, user must remove 5 characters.

**Comment by jtblin** [comment]
Ok, thanks. I am not going to introduce a breaking change right now. I'm waiting on chart.js 2.0 final release at which point there will be breaking changes so I'll publish a 1.0 for this library and can review this then.

**Comment by jtblin** [comment]
Thanks for the idea, this is now done on [chartjs-2.0 branch](https://github.com/jtblin/angular-chart.js/tree/chartjs-2.0) and will be published soon.

**Comment by drpicox** [comment]
Nice!

**Pull request closed without merging**
