### PR TITLE
Change angular dependency version to 1.2.x-1.4.x range.

### PR DESCRIPTION
**Pull request by MihaiDinculescu**

### CODE REVIEW

**Comment by MihaiDinculescu** [comment]
Changed to  `>= 1.2` to accommodate https://github.com/jtblin/angular-chart.js/issues/338 too.

**Comment by jtblin** [comment]
Thanks. Not sure why but the tests are failing. 
Also you'd need to squash all the commits into one.

**Comment by MihaiDinculescu** [comment]
The 'watches the attributes of the chart' test fails in Angular 1.2 only. I remember that Angular 1.3 introduced some breaking changes to `$watch` so it might be related.

As before, all tests fail in Angular 1.5 for some reason.

**Comment by jtblin** [comment]
Maybe need to resolve angiular and angular-mock in bower so that it picks 1.4.9 by default. There is an optional resolve object. Otherwise I'm considering to ditch bower for managing my dependencies and use npm instead...

**Comment by MihaiDinculescu** [comment]
How about having `"angular": ">=1.2"` under `dependencies`, but `"angular": "1.4.x"` under `devDependencies`? It seems to be working locally.

**Comment by MihaiDinculescu** [comment]
Any feedback on this?

**Comment by jtblin** [comment]
Sorry for the lag @MihaiDinculescu, I've fixed the test that was having issue with `1.5.x` instead and updated bower and npm files. Published as `0.10.2`. This shouldn't be an issue anymore.

**Pull request closed without merging**
