### PR TITLE
Change version of Chartjs on Package JSON

### PR DESCRIPTION
**Pull request by gerardoepp**
Since version +2.4.0 chart.js allow to change the cursor to pointer when hover in chart legends.

### CODE REVIEW

**Comment by Boosten** [comment]
@gerardoepp you're not going to continue on the PR anymore?

**Comment by gerardoepp** [comment]
Hi man, yeah, i have to test before the pull request

**Comment by gerardoepp** [comment]
Isn't weird comparing rendered graphs images for a module related with angular chart.js integration?, what's the point with this image comparison tests?, isn't responsability of chart.js?, I think you should only test things related with angular integration. This tests should be remove in order to be able to update minor version of chart.js, should be 2.x.x and not frozen on 2.3

**Comment by jtblin** [comment]
Just wow, commenting out all the tests 👎

**Pull request closed without merging**
