### PR TITLE
Adds inline array annotation for directives's dependency injection to prevent $injector:unpr error.

### PR DESCRIPTION
**Pull request by augustoabreu**
We are minifing our files and this is crashing all the charts.

### CODE REVIEW

**Comment by SuperGouge** [comment]
You should use the files from the ``dist`` folder as they contain the annotations that are automatically added on build: jantimon/angular-chart.js@04b7545bf26b55148afb41a625d8b2a109edbc8b.

**Comment by jtblin** [comment]
Yes exactly as @SuperGouge said. This change is not required.

**Comment by maxisam** [comment]
Ah... not everyone uses that dist one. Why not just add array notation ? besides, you have array notation everywhere already. What is the down side of adding this ?

**Comment by SuperGouge** [comment]
The files in the ``dist`` folder are the only ones you should use. The file at the root is just the source. The ``main`` property of the ``package.json`` even specifies ``dist/angular-chart.js``.

**Comment by maxisam** [comment]
I think you and I are talking about different things. Yes, I know I can use the one in dist.

**Comment by SuperGouge** [comment]
Ok, then I fail to see the problem, sorry.

**Comment by maxisam** [comment]
It is more like code style consistency, but I am not a contributor in this project. I guess it doesn't really matter.

**Pull request closed without merging**
