### PR TITLE
added hover event

### PR DESCRIPTION
**Pull request by idangozlan**
- dist not created
+ docs updated

Useful for hover points.

### CODE REVIEW

**Comment by jtblin** [comment]
Hey, sorry for the lag. Looks mostly good except for whitespace issue that I can always fix later, so no worries about that. Only thing is it looks like a bit of duplication with the `onclick` code, maybe you could make this dynamic?

```
['hover', 'click'].forEach(function (action) {
  if (scope[action]) ....
```

It will be a bit harder to follow which I don't really like but can remove duplication which I like and reduce weight. What do you think?

**Comment by idangozlan** [comment]
Hi, updated.

**Comment by jtblin** [comment]
Sorry for the lag. Thank you for the update. 

Sorry to be a pain but I don't think the `switch` case is needed and I don't really like assigning functions to variables e.g. `var func = function ...`. Can you just do `cvs[action]` as originally discussed? It's less verbose and fits better with the rest of the code.

Also it would be great if you could fix the space issues as it breaks `jscs` check: https://travis-ci.org/jtblin/angular-chart.js/builds/55922261 so the CI isn't able to run the tests. I use 2 spaces for indentation (no tabs). You can run the linting, code style check and tests locally by running `npm install` then `gulp check`.

After that I will merge asap.

**Comment by idangozlan** [comment]
Hi,

It's impossible to do `cvs[action]` due to events name which are not the same as our attributes.

If I didn't got you correctly, please let me know..

Thanks.

**Comment by jtblin** [comment]
Ok, overlooked that. Can you just change to a if / else then?

**Comment by idangozlan** [comment]
Done...

**Comment by jtblin** [comment]
Awesome, thanks a ton for the contribution and for your patience!

**Pull request merged**
