### PR TITLE
updated chartjs dependencies

### PR DESCRIPTION
**Pull request by niemyjski**
### Pull Request check-list

- [ ] Run `gulp test` to ensure there are no linting, or style issues and all tests pass.
- [ ] Squash your commits into a few commits only.
- [ ] Make sure the commit message is short, concise and descriptive of the issues you're fixing.
- [ ] Avoid mixing up multiple issues and/or features, open one pull request for each issue.
- [ ] Have you updated the documentation and / or examples?
- [ ] Have you included a new test?

### CODE REVIEW

**Comment by niemyjski** [comment]
The dev dependencies could use some love. This fixes bower resolves

**Comment by jtblin** [comment]
Thanks, could you pls do the same in package.json for npm as well and rebase?

**Comment by niemyjski** [comment]
I looked and it was already updated.

**Comment by jtblin** [comment]
Actually don't bother, that was done as part of #382 to support horizontal bar chart.

**Pull request closed without merging**
